- name: Test of performent Phonebook-app
  hosts: preprod
  gather_facts: true
  become: true

  vars_files:
    - "group-vars/main.yml"

  pre_tasks:
    - name: upgrade all packages
      yum:
        name: '*'
        state: latest
        exclude: kernel*,foo*

    - name: Copy file planTest.jmx
      template:
        src: jmeter/planTest.j2
        dest: "{{ house }}/planTest.jmx"
        owner: centos
        remote_src: no

    - name: Copy file file.jtl
      copy:
        src: jmeter/file.jtl
        dest: "{{ house }}"
        owner: centos
        remote_src: no

  roles:
    - role: geerlingguy.java
      when: "ansible_os_family == 'RedHat'"
      java_packages:
        - java-1.8.0-openjdk

  tasks:
    - name: Download apache-jmeter-5.3
      get_url:
        url: {{ http_jmeter }}
        dest: {{ house }}

    - name: Unarchive a file that is already on the remote machine
      unarchive:
        src: {{ house }}/{{ paquet_jmeter }}
        dest: {{ house }}
        remote_src: yes

    - name: Run a command shell
      shell: {{ run_jmeter }}/bin/jmeter.sh -n -t {{ house }}/planTest.jmx -l {{ house }}/file.jtl
      args:
        warn: no
